packages:
  - packages/*
allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@turbo/darwin-64@2.10.6'
  - '@turbo/darwin-arm64@2.10.6'
  - '@turbo/linux-64@2.10.6'
  - '@turbo/linux-arm64@2.10.6'
  - '@turbo/windows-64@2.10.6'
  - '@turbo/windows-arm64@2.10.6'
  - turbo@2.10.6
  - '@biomejs/biome@2.5.7'
  - '@biomejs/cli-darwin-arm64@2.5.7'
  - '@biomejs/cli-darwin-x64@2.5.7'
  - '@biomejs/cli-linux-arm64-musl@2.5.7'
  - '@biomejs/cli-linux-arm64@2.5.7'
  - '@biomejs/cli-linux-x64-musl@2.5.7'
  - '@biomejs/cli-linux-x64@2.5.7'
  - '@biomejs/cli-win32-arm64@2.5.7'
  - '@biomejs/cli-win32-x64@2.5.7'
onlyBuiltDependencies:
  - '@biomejs/biome'
  - esbuild
