name: Build and Test
permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: latest

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: Install dependencies
        run: pnpm install --ignore-scripts

      - name: Build all packages
        run: pnpm build
      - name: Test all packages
        run: pnpm test
        env:
          BEGIT_GH_API_KEY: ${{ secrets.GITHUB_TOKEN }}
